name: Helm Deploy by LaputaCloud
description: Deploys a helm chart
author: laputacloudco
branding:
  icon: upload
  color: blue
inputs:
  release:
    description: Helm release name. Will be combined with track if set. (required)
    required: true
  repository:
    description: The URL for a helm repo to come from. (optional)
    required: false
  namespace:
    description: Kubernetes namespace name. (required)
    required: true
  chart:
    description: Helm chart path. (required)
    required: true
  values:
    description: Helm chart values, expected to be a YAML or JSON string.
    required: false
  task:
    description: Task name. If the task is "remove" it will remove the configured
      helm release.
    required: false
  dry-run:
    description: Simulate an upgrade.
    required: false
  atomic:
    description: If true, upgrade process rolls back changes made in case of failed upgrade. Defaults to true.
    required: false
  token:
    description: Github repository token. If included and the event is a deployment
      the deployment_status event will be fired.
    required: false
  value-files:
    description: Additional value files to apply to the helm chart. Expects JSON encoded
      array or a string.
    required: false
  secrets:
    description: Secret variables to include in value file interpolation. Expects
      JSON encoded map.
    required: false
  version:
    description: Version of the app, usually commit sha works here.
    required: false
runs:
  using: docker
  image: Dockerfile
